import type { CatalogEntry } from "./types";

/**
 * 候補店カタログ。エリアごとに 4〜5 件を用意し、計 22 件を収録。
 * 既存の新宿 5 件（千里香 / 肉ビストロ灯 / 魚や舟政 / 酒場つむぎ堂 / 陽ノ鳥）はそのまま流用。
 */
export const CATALOG: CatalogEntry[] = [
  // ── 新宿 ─────────────────────────────────────────────────────
  {
    name: "千里香",
    genre: "中華",
    url: "https://maps.app.goo.gl/mMHdTBdnsFcf7cZE6",
    area: "新宿",
    budget: "5,000〜6,000円",
    budgetMin: 5000,
    budgetMax: 6000,
    googleRating: "4.1",
    walkingMinutes: 8,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "ガチ中華で会話のネタになる",
    recommendPoint: "中華好きや少し変わったお店に行きたい時に良さそう",
    cautionPoint: "Google評価はやや低めだが、個人的には候補に入れる価値あり",
    emoji: "🇨🇳",
  },
  {
    name: "肉ビストロ灯",
    genre: "ビストロ",
    url: "https://maps.app.goo.gl/K8c8o2BGbB1sa4U6A",
    area: "新宿",
    budget: "5,000〜6,000円",
    budgetMin: 5000,
    budgetMax: 6000,
    googleRating: "4.5",
    walkingMinutes: 7,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "コースのコスパが良い",
    recommendPoint: "料理の満足度が高そうで、少しおしゃれな会に使いやすい",
    cautionPoint: "ワイン中心なので、相手のお酒の好みによっては注意",
    emoji: "🍷",
  },
  {
    name: "魚や舟政",
    genre: "魚",
    url: "https://maps.app.goo.gl/fCgwpsjwF9mXj1qZ6",
    area: "新宿",
    budget: "5,000〜6,000円",
    budgetMin: 5000,
    budgetMax: 6000,
    googleRating: "4.5",
    walkingMinutes: 6,
    hasNomihodai: true,
    hasPrivateRoom: true,
    memo: "個室が多くて会話しやすい",
    recommendPoint: "落ち着いて話したい会や、無難にまとめたい時に良さそう",
    cautionPoint: "個性は強くなく、普通の居酒屋寄り",
    emoji: "🍻",
  },
  {
    name: "酒場 つむぎ堂",
    genre: "なんでも系",
    url: "https://maps.app.goo.gl/yvu4gsbYHskWR9tdA",
    area: "新宿",
    budget: "5,000〜6,000円",
    budgetMin: 5000,
    budgetMax: 6000,
    googleRating: "4.6",
    walkingMinutes: 9,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "人気なので早めの予約が必要",
    recommendPoint: "雰囲気がよく、若手飲みやカジュアルな会社飲みに使いやすい",
    cautionPoint: "混みやすそうなので早めの確認が必要",
    emoji: "👩‍💼",
  },
  {
    name: "陽ノ鳥",
    genre: "焼き鳥",
    url: "https://maps.app.goo.gl/piyRmavyxdkmiUeG6",
    area: "新宿",
    budget: "5,000〜6,000円",
    budgetMin: 5000,
    budgetMax: 6000,
    googleRating: "4.5",
    walkingMinutes: 8,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "焼き鳥で外しにくい",
    recommendPoint:
      "焼き鳥なので好き嫌いが分かれにくく、会社飲みにも使いやすい",
    cautionPoint: "大人数の場合は席の取りやすさを確認した方が良い",
    emoji: "🐔",
  },

  // ── 渋谷 ─────────────────────────────────────────────────────
  {
    name: "炭火焼鳥 鳥つぐ",
    genre: "焼き鳥",
    url: "#placeholder",
    area: "渋谷",
    budget: "4,500〜5,500円",
    budgetMin: 4500,
    budgetMax: 5500,
    googleRating: "4.4",
    walkingMinutes: 5,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "カウンターで職人と話しながら",
    recommendPoint: "少人数の会話重視の飲みに合いそう",
    cautionPoint: "席数が少なく予約必須",
    emoji: "🍢",
  },
  {
    name: "ワインバル ぶどう座",
    genre: "ワインバル",
    url: "#placeholder",
    area: "渋谷",
    budget: "5,500〜7,000円",
    budgetMin: 5500,
    budgetMax: 7000,
    googleRating: "4.3",
    walkingMinutes: 4,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "グラスワインの種類が豊富",
    recommendPoint: "デートやおしゃれ会、女性比率高めの会に使いやすい",
    cautionPoint: "音楽が大きめで賑やか",
    emoji: "🍷",
  },
  {
    name: "渋谷もつ鍋 結",
    genre: "もつ鍋",
    url: "#placeholder",
    area: "渋谷",
    budget: "4,000〜5,000円",
    budgetMin: 4000,
    budgetMax: 5000,
    googleRating: "4.2",
    walkingMinutes: 6,
    hasNomihodai: true,
    hasPrivateRoom: true,
    memo: "個室確保でゆっくり",
    recommendPoint: "冬場や会話メインの会で重宝",
    cautionPoint: "夏場はやや汗ばむ",
    emoji: "🍲",
  },
  {
    name: "PIZZERIA トラム",
    genre: "イタリアン",
    url: "#placeholder",
    area: "渋谷",
    budget: "3,500〜4,500円",
    budgetMin: 3500,
    budgetMax: 4500,
    googleRating: "4.4",
    walkingMinutes: 7,
    hasNomihodai: false,
    hasPrivateRoom: false,
    memo: "石窯ピザがウリ",
    recommendPoint: "ライトな飲みや二次会に使いやすい",
    cautionPoint: "飲み放題プランがない",
    emoji: "🍕",
  },
  {
    name: "魚介酒場 とびうお",
    genre: "魚介居酒屋",
    url: "#placeholder",
    area: "渋谷",
    budget: "5,000〜6,500円",
    budgetMin: 5000,
    budgetMax: 6500,
    googleRating: "4.5",
    walkingMinutes: 5,
    hasNomihodai: true,
    hasPrivateRoom: true,
    memo: "魚は産地直送",
    recommendPoint: "魚好きな上司との会食にハマる",
    cautionPoint: "週末は混雑",
    emoji: "🐟",
  },

  // ── 池袋 ─────────────────────────────────────────────────────
  {
    name: "餃子酒場 こだま",
    genre: "餃子・中華",
    url: "#placeholder",
    area: "池袋",
    budget: "3,000〜4,000円",
    budgetMin: 3000,
    budgetMax: 4000,
    googleRating: "4.3",
    walkingMinutes: 4,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "餃子の種類が豊富",
    recommendPoint: "コスパ重視の会社飲みや友達飲みに最適",
    cautionPoint: "店内が賑やかで会話しづらいことも",
    emoji: "🥟",
  },
  {
    name: "個室和食 杉乃葉",
    genre: "和食",
    url: "#placeholder",
    area: "池袋",
    budget: "5,500〜7,000円",
    budgetMin: 5500,
    budgetMax: 7000,
    googleRating: "4.4",
    walkingMinutes: 6,
    hasNomihodai: true,
    hasPrivateRoom: true,
    memo: "全席個室で接待向き",
    recommendPoint: "落ち着いた会食や懇親会で使いやすい",
    cautionPoint: "客単価高めなので予算注意",
    emoji: "🍱",
  },
  {
    name: "炭火焼ホルモン 灯火",
    genre: "焼肉・ホルモン",
    url: "#placeholder",
    area: "池袋",
    budget: "4,500〜6,000円",
    budgetMin: 4500,
    budgetMax: 6000,
    googleRating: "4.5",
    walkingMinutes: 5,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "ホルモンが新鮮",
    recommendPoint: "肉好きな同僚との飲み会で盛り上がる",
    cautionPoint: "煙が出るので服装に注意",
    emoji: "🥩",
  },
  {
    name: "クラフトビアバル ホップ",
    genre: "クラフトビール",
    url: "#placeholder",
    area: "池袋",
    budget: "4,000〜5,000円",
    budgetMin: 4000,
    budgetMax: 5000,
    googleRating: "4.2",
    walkingMinutes: 7,
    hasNomihodai: false,
    hasPrivateRoom: false,
    memo: "常時 12 種のクラフトビール",
    recommendPoint: "ビール好きな友達飲み・二次会にぴったり",
    cautionPoint: "飲み放題プラン無し",
    emoji: "🍺",
  },

  // ── 恵比寿 ───────────────────────────────────────────────────
  {
    name: "恵比寿 鮨 つきよみ",
    genre: "寿司",
    url: "#placeholder",
    area: "恵比寿",
    budget: "8,000〜10,000円",
    budgetMin: 8000,
    budgetMax: 10000,
    googleRating: "4.7",
    walkingMinutes: 5,
    hasNomihodai: false,
    hasPrivateRoom: true,
    memo: "夜はおまかせコースのみ",
    recommendPoint: "重要な会食や記念日デートに",
    cautionPoint: "予算と予約難易度ともに高め",
    emoji: "🍣",
  },
  {
    name: "ビストロ ル・コキャージュ",
    genre: "ビストロ",
    url: "#placeholder",
    area: "恵比寿",
    budget: "6,000〜7,500円",
    budgetMin: 6000,
    budgetMax: 7500,
    googleRating: "4.5",
    walkingMinutes: 4,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "肉とワインのお店",
    recommendPoint: "デートや少しおしゃれな会食で外しにくい",
    cautionPoint: "席間が近めなので落ち着いた会には向かない場合あり",
    emoji: "🥂",
  },
  {
    name: "おでん きほん",
    genre: "おでん・和食",
    url: "#placeholder",
    area: "恵比寿",
    budget: "4,500〜6,000円",
    budgetMin: 4500,
    budgetMax: 6000,
    googleRating: "4.3",
    walkingMinutes: 6,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "出汁の効いたおでんが看板",
    recommendPoint: "落ち着いた会話メインの飲みに合う",
    cautionPoint: "夏場はやや穴場",
    emoji: "🍢",
  },
  {
    name: "韓国料理 ハヌル",
    genre: "韓国料理",
    url: "#placeholder",
    area: "恵比寿",
    budget: "4,000〜5,500円",
    budgetMin: 4000,
    budgetMax: 5500,
    googleRating: "4.4",
    walkingMinutes: 5,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "サムギョプサルが人気",
    recommendPoint: "友達飲みや女子会に強い",
    cautionPoint: "週末は予約必須",
    emoji: "🌶️",
  },

  // ── 銀座 ─────────────────────────────────────────────────────
  {
    name: "銀座 鉄板 美津庵",
    genre: "鉄板焼き",
    url: "#placeholder",
    area: "銀座",
    budget: "9,000〜12,000円",
    budgetMin: 9000,
    budgetMax: 12000,
    googleRating: "4.6",
    walkingMinutes: 4,
    hasNomihodai: false,
    hasPrivateRoom: true,
    memo: "目の前で焼いてくれる",
    recommendPoint: "重要な接待や記念日に",
    cautionPoint: "客単価が高く予算配慮必須",
    emoji: "🍳",
  },
  {
    name: "和酒場 千歳",
    genre: "和食居酒屋",
    url: "#placeholder",
    area: "銀座",
    budget: "5,500〜7,000円",
    budgetMin: 5500,
    budgetMax: 7000,
    googleRating: "4.4",
    walkingMinutes: 5,
    hasNomihodai: true,
    hasPrivateRoom: true,
    memo: "日本酒の品揃え豊富",
    recommendPoint: "上司との会食や懇親会で安定",
    cautionPoint: "土日休みなので注意",
    emoji: "🍶",
  },
  {
    name: "ワインバー グラン",
    genre: "ワインバー",
    url: "#placeholder",
    area: "銀座",
    budget: "5,000〜6,500円",
    budgetMin: 5000,
    budgetMax: 6500,
    googleRating: "4.5",
    walkingMinutes: 3,
    hasNomihodai: false,
    hasPrivateRoom: false,
    memo: "落ち着いた大人向け",
    recommendPoint: "二次会やデートにぴったり",
    cautionPoint: "飲み放題なし、料理は軽め",
    emoji: "🍷",
  },
  {
    name: "中華 桃源郷",
    genre: "中華",
    url: "#placeholder",
    area: "銀座",
    budget: "6,000〜8,000円",
    budgetMin: 6000,
    budgetMax: 8000,
    googleRating: "4.3",
    walkingMinutes: 6,
    hasNomihodai: true,
    hasPrivateRoom: true,
    memo: "個室で本格中華コース",
    recommendPoint: "幅広い世代の懇親会に",
    cautionPoint: "辛い料理多め、苦手な人は事前確認",
    emoji: "🥡",
  },
];
