import type { EventCondition, Restaurant } from "./types";

export const STORAGE_KEYS = {
  condition: "nomiris.condition.v1",
  restaurants: "nomiris.restaurants.v1",
} as const;

export const DEFAULT_CONDITION: EventCondition = {
  title: "新宿1軒目候補案",
  area: "新宿",
  scene: "会社飲み",
  peopleCount: 4,
  budgetLimit: 6000,
  walkingMinutes: 10,
  nomihodai: "あり",
  privateRoom: "どちらでも",
  atmosphere: "会話しやすい",
  participants: "上司・若手混合",
  priorities: "アクセス、コスパ、会話しやすさ",
  avoidPoints: "うるさすぎる、高すぎる、駅から遠い",
  tone: "丁寧",
};

export const DEFAULT_RESTAURANTS: Restaurant[] = [
  {
    id: "seed-1",
    name: "千里香",
    genre: "中華",
    url: "https://maps.app.goo.gl/mMHdTBdnsFcf7cZE6",
    area: "新宿",
    budget: "5,000〜6,000円",
    googleRating: "4.1",
    tabelogRating: "3.45",
    walkingMinutes: 8,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "ガチ中華で会話のネタになる",
    recommendPoint: "中華好きや少し変わったお店に行きたい時に良さそう",
    cautionPoint: "Google評価はやや低めだが、個人的には候補に入れる価値あり",
    emoji: "🇨🇳",
    selected: true,
  },
  {
    id: "seed-2",
    name: "肉ビストロ灯",
    genre: "ビストロ",
    url: "https://maps.app.goo.gl/K8c8o2BGbB1sa4U6A",
    area: "新宿",
    budget: "5,000〜6,000円",
    googleRating: "4.5",
    tabelogRating: "3.40",
    walkingMinutes: 7,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "コースのコスパが良い",
    recommendPoint: "料理の満足度が高そうで、少しおしゃれな会に使いやすい",
    cautionPoint: "ワイン中心なので、相手のお酒の好みによっては注意",
    emoji: "🍷",
    selected: true,
  },
  {
    id: "seed-3",
    name: "魚や舟政",
    genre: "魚",
    url: "https://maps.app.goo.gl/fCgwpsjwF9mXj1qZ6",
    area: "新宿",
    budget: "5,000〜6,000円",
    googleRating: "4.5",
    tabelogRating: "3.36",
    walkingMinutes: 6,
    hasNomihodai: true,
    hasPrivateRoom: true,
    memo: "個室が多くて会話しやすい",
    recommendPoint: "落ち着いて話したい会や、無難にまとめたい時に良さそう",
    cautionPoint: "個性は強くなく、普通の居酒屋寄り",
    emoji: "🍻",
    selected: true,
  },
  {
    id: "seed-4",
    name: "酒場 つむぎ堂",
    genre: "なんでも系",
    url: "https://maps.app.goo.gl/yvu4gsbYHskWR9tdA",
    area: "新宿",
    budget: "5,000〜6,000円",
    googleRating: "4.6",
    tabelogRating: "3.38",
    walkingMinutes: 9,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "人気なので早めの予約が必要",
    recommendPoint: "雰囲気がよく、若手飲みやカジュアルな会社飲みに使いやすい",
    cautionPoint: "混みやすそうなので早めの確認が必要",
    emoji: "👩‍💼",
    selected: true,
  },
  {
    id: "seed-5",
    name: "陽ノ鳥",
    genre: "焼き鳥",
    url: "https://maps.app.goo.gl/piyRmavyxdkmiUeG6",
    area: "新宿",
    budget: "5,000〜6,000円",
    googleRating: "4.5",
    tabelogRating: "3.35",
    walkingMinutes: 8,
    hasNomihodai: true,
    hasPrivateRoom: false,
    memo: "焼き鳥で外しにくい",
    recommendPoint:
      "焼き鳥なので好き嫌いが分かれにくく、会社飲みにも使いやすい",
    cautionPoint: "大人数の場合は席の取りやすさを確認した方が良い",
    emoji: "🐔",
    selected: true,
  },
];
